### ISSUE TITLE
Training stops after 3 epochs (wrong gast version?)

### ISSUE THREAD

**Issue by GourmandGuedj** [Common-Voice/commonvoice-fr#87] opened 2020-01-16 15:10 UTC
Hello there, 
My training seems to stop after 3 epochs, and it seems related to the version of gast installed:

```
Epoch 3 | Validation | Elapsed Time: 0:00:17 | Steps: 13 | Loss: 48.163957 | Dataset: /mnt/extracted/data/African_Accented_French/African_Accented_French/African_Accented_French_dev.csv
I Early stop triggered as (for last 4 steps) validation loss: 37.242888 with standard deviation: 0.310681 and mean: 36.303010
I FINISHED optimization in 1:22:21.241841
WARNING:tensorflow:Entity <bound method LSTMBlockWrapper.call of <tensorflow.contrib.rnn.python.ops.lstm_ops.LSTMBlockFusedCell object at 0x7f3a003c8cf8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method LSTMBlockWrapper.call of <tensorflow.contrib.rnn.python.ops.lstm_ops.LSTMBlockFusedCell object at 0x7f3a003c8cf8>>: AttributeError: module 'gast' has no attribute 'Num'
W0116 14:20:37.469725 139891645953856 ag_logging.py:145] Entity <bound method LSTMBlockWrapper.call of <tensorflow.contrib.rnn.python.ops.lstm_ops.LSTMBlockFusedCell object at 0x7f3a003c8cf8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method LSTMBlockWrapper.call of <tensorflow.contrib.rnn.python.ops.lstm_ops.LSTMBlockFusedCell object at 0x7f3a003c8cf8>>: AttributeError: module 'gast' has no attribute 'Num'
INFO:tensorflow:Restoring parameters from /mnt/checkpoints/best_dev-18787
I0116 14:20:37.636511 139891645953856 saver.py:1280] Restoring parameters from /mnt/checkpoints/best_dev-18787
I Restored variables from best validation checkpoint at /mnt/checkpoints/best_dev-18787, step 18787
Testing model on /mnt/extracted/data/M-AILABS/fr_FR/fr_FR_test.csv
Test epoch | Steps: 0 | Elapsed Time: 0:00:00                                                                     Fatal Python error: Segmentation fault

Thread 0x00007f3a01f0a700 (most recent call first):

Thread 0x00007f3a0380d700 (most recent call first):
  File "/usr/lib/python3.6/threading.py", line 295 in wait
  File "/usr/lib/python3.6/queue.py", line 164 in get
  File "/home/trainer/ds-train/lib/python3.6/site-packages/tensorflow/python/summary/writer/event_file_wrifr/train.sh: line 49:    51 Segmentation fault      (core dumped) python -u DeepSpeech.py --show_progressbar True --use_cudnn_rnn True --automatic_mixed_precision True --alphabet_config_path /mnt/models/alphabet.txt --lm_binary_path /mnt/lm/lm.binary --lm_trie_path /mnt/lm/trie --feature_cache /mnt/sources/feature_cache --train_files ${all_train_csv} --dev_files ${all_dev_csv} --test_files ${all_test_csv} --train_batch_size ${BATCH_SIZE} --dev_batch_size ${BATCH_SIZE} --test_batch_size ${BATCH_SIZE} --n_hidden ${N_HIDDEN} --epochs ${EPOCHS} --learning_rate ${LEARNING_RATE} --dropout_rate ${DROPOUT} --lm_alpha ${LM_ALPHA} --lm_beta ${LM_BETA} ${EARLY_STOP_FLAG} --checkpoint_dir /mnt/checkpoints/ --export_dir /mnt/models/ --export_language "fra"
```

Seems related to [this TensorFlow issue](https://github.com/tensorflow/tensorflow/issues/32319), which is why I'm thinking about a wrong version of Gast, but did anyone came across this issue already and is there a way to fix properly? (maybe define the right gast version in the dockerfile?) Or maybe it is something else?

**Comment by lissyx** [comment] 2020-01-16 15:12
>  (maybe define the right gast version in the dockerfile?)

We should have a fixed-version for Gast in requirements.txt already, maybe this needs to be fixed?

Have you changed the DeepSpeech branch ?

**Comment by lissyx** [comment] 2020-01-16 15:21
@GourmandGuedj It's likely something I already ran into, maybe I forgot to fix it or I got lucky. Looking at the tensorflow ticket, it definitively reminds me of something.

**Comment by lissyx** [comment] 2020-01-16 15:25
@GourmandGuedj Can you check your language model as well ? It fails at step 0 of the test epoch, it's possible this is what is broken.

Do you have build / run logs, we should verify `ds_ctcdecoder` package setup.

**Comment by GourmandGuedj** [comment] 2020-01-16 15:29
@lissyx the full logs of run prior training
```
docker run --tty --runtime=nvidia --mount type=bind,src=/home/gabrielcloud75/hostdir,dst=/mnt ba5e50a23ee8
+ dirname /home/trainer/run.sh
+ export PATH=/home/trainer:/home/trainer/kenlm/build/bin/:/home/trainer/ds-train/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ env
ENGLISH_COMPATIBLE=0
HOSTNAME=1c68f82bba86
DS_SHA1=dab5183a985652f46b4b2dadde2d4df08e5fa4bf
LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
HOME=/home/trainer
DROPOUT=0.3
DS_BRANCH=b3787ee1888322dc68b8b3e4a5f6f859ba9dd05e
CUDA_VERSION=10.0.130
MODEL_LANGUAGE=fr
NVIDIA_REQUIRE_CUDA=cuda>=10.0 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=410,driver<411
N_HIDDEN=2048
NVIDIA_DRIVER_CAPABILITIES=compute,utility
TERM=xterm
BEAM_WIDTH=500
LEARNING_RATE=0.0001
PATH=/home/trainer:/home/trainer/kenlm/build/bin/:/home/trainer/ds-train/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
CUDA_PKG_VERSION=10-0=10.0.130-1
LANG=C.UTF-8
CUDNN_VERSION=7.6.5.32
DEBIAN_FRONTEND=noninteractive
VIRTUAL_ENV_NAME=ds-train
BATCH_SIZE=96
LM_EVALUATE_RANGE=
LM_ALPHA=0.65
VIRTUAL_ENV=/home/trainer/ds-train
LM_BETA=1.45
EPOCHS=60
PWD=/home/trainer
HOMEDIR=/home/trainer
EARLY_STOP=1
NVIDIA_VISIBLE_DEVICES=all
NCCL_VERSION=2.4.8
DS_DIR=/home/trainer/ds
+ checks.sh
+ sudo id
uid=0(root) gid=0(root) groups=0(root)
+ sudo /sbin/ldconfig
+ nvidia-smi
Thu Jan 16 12:53:39 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P0    37W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
++ find /mnt/ -maxdepth 1 -type d
+ for dir in $(find /mnt/ -maxdepth 1 -type d)
+ echo 'Checking /mnt/ ...'
Checking /mnt/ ...
+ '[' '!' -w /mnt/ ']'
+ for dir in $(find /mnt/ -maxdepth 1 -type d)
+ echo 'Checking /mnt/lm ...'
Checking /mnt/lm ...
+ '[' '!' -w /mnt/lm ']'
+ for dir in $(find /mnt/ -maxdepth 1 -type d)
+ echo 'Checking /mnt/models ...'
Checking /mnt/models ...
+ '[' '!' -w /mnt/models ']'
+ for dir in $(find /mnt/ -maxdepth 1 -type d)
+ echo 'Checking /mnt/sources ...'
Checking /mnt/sources ...
+ '[' '!' -w /mnt/sources ']'
+ for dir in $(find /mnt/ -maxdepth 1 -type d)
+ echo 'Checking /mnt/tmp ...'
Checking /mnt/tmp ...
+ '[' '!' -w /mnt/tmp ']'
+ for dir in $(find /mnt/ -maxdepth 1 -type d)
+ echo 'Checking /mnt/extracted ...'
Checking /mnt/extracted ...
+ '[' '!' -w /mnt/extracted ']'
+ for dir in $(find /mnt/ -maxdepth 1 -type d)
+ echo 'Checking /mnt/checkpoints ...'
Checking /mnt/checkpoints ...
+ '[' '!' -w /mnt/checkpoints ']'
+ for subdir in sources extracted checkpoints models lm tmp
+ '[' '!' -d /mnt/sources ']'
+ for subdir in sources extracted checkpoints models lm tmp
+ '[' '!' -d /mnt/extracted ']'
+ for subdir in sources extracted checkpoints models lm tmp
+ '[' '!' -d /mnt/checkpoints ']'
+ for subdir in sources extracted checkpoints models lm tmp
+ '[' '!' -d /mnt/models ']'
+ for subdir in sources extracted checkpoints models lm tmp
+ '[' '!' -d /mnt/lm ']'
+ for subdir in sources extracted checkpoints models lm tmp
+ '[' '!' -d /mnt/tmp ']'
+ mkdir /mnt/extracted/data/
mkdir: cannot create directory ‘/mnt/extracted/data/’: File exists
+ true
+ export TMP=/mnt/tmp
+ export TEMP=/mnt/tmp
+ fr/run.sh
+ fr/import_cvfr.sh
+ pushd /home/trainer/ds/
~/ds ~
+ '[' '!' -f /mnt/sources/fr.tar.gz ']'
++ sha1sum --binary /mnt/sources/fr.tar.gz
++ awk '{ print $1 }'
+ sha1=e4935b160fb601c00069c45e6f1ff9f130912955
+ '[' e4935b160fb601c00069c45e6f1ff9f130912955 '!=' e4935b160fb601c00069c45e6f1ff9f130912955 ']'
+ '[' 0 = 1 ']'
+ '[' '!' -f /mnt/extracted/data/cv-fr/clips/train.csv ']'
+ popd

+ fr/import_lingualibre.sh
+ pushd /home/trainer/ds/
~/ds ~
+ '[' 0 = 1 ']'
+ '[' '!' -f /mnt/extracted/data/lingualibre/lingua_libre_Q21-fra-French_train.csv ']'
+ popd
~
+ fr/import_slr57.sh
+ pushd /home/trainer/ds/
~/ds ~
+ '[' 0 = 1 ']'
+ '[' '!' -f /mnt/extracted/data/African_Accented_French/African_Accented_French/African_Accented_French_train.csv ']'
+ popd
~
+ fr/import_m-ailabs.sh
+ pushd /home/trainer/ds/
~/ds ~
+ '[' 0 = 1 ']'
+ '[' '!' -f /mnt/extracted/data/M-AILABS/fr_FR/fr_FR_train.csv ']'
+ popd
~
+ generate_alphabet.sh
+ pushd /home/trainer/ds/
~/ds ~
++ find /mnt/extracted/data/ -type f -name '*train.csv' -printf %p,
++ sed -e 's/,$//g'
+ all_train_csv=/mnt/extracted/data/M-AILABS/fr_FR/fr_FR_train.csv,/mnt/extracted/data/lingualibre/lingua_libre_Q21-fra-French_train.csv,/mnt/extracted/data/cv-fr/clips/train.csv,/mnt/extracted/data/African_Accented_French/African_Accented_French/African_Accented_French_train.csv
++ find /mnt/extracted/data/ -type f -name '*dev.csv' -printf %p,
++ sed -e 's/,$//g'
+ all_dev_csv=/mnt/extracted/data/M-AILABS/fr_FR/fr_FR_dev.csv,/mnt/extracted/data/lingualibre/lingua_libre_Q21-fra-French_dev.csv,/mnt/extracted/data/cv-fr/clips/dev.csv,/mnt/extracted/data/African_Accented_French/African_Accented_French/African_Accented_French_dev.csv
++ find /mnt/extracted/data/ -type f -name '*test.csv' -printf %p,
++ sed -e 's/,$//g'
+ all_test_csv=/mnt/extracted/data/M-AILABS/fr_FR/fr_FR_test.csv,/mnt/extracted/data/lingualibre/lingua_libre_Q21-fra-French_test.csv,/mnt/extracted/data/cv-fr/clips/test.csv,/mnt/extracted/data/African_Accented_French/African_Accented_French/African_Accented_French_test.csv
+ '[' '!' -f /mnt/models/alphabet.txt ']'
+ popd
~
+ fr/build_lm.sh
+ pushd /mnt/extracted
/mnt/extracted ~
+ '[' 0 = 1 ']'
+ '[' '!' -f wiki_fr_lower.txt ']'
+ '[' '!' -f debats-assemblee-nationale.txt ']'
+ '[' 0 = 1 ']'
+ cat wiki_fr_lower.txt debats-assemblee-nationale.txt
+ '[' '!' -f /mnt/lm/lm.binary ']'
+ '[' '!' -f /mnt/lm/trie ']'
+ '[' 0 = 1 ']'
+ popd
~
+ fr/train.sh
+ pushd /home/trainer/ds/
~/ds ~
++ find /mnt/extracted/data/ -type f -name '*train.csv' -printf %p,
++ sed -e 's/,$//g'
+ all_train_csv=/mnt/extracted/data/M-AILABS/fr_FR/fr_FR_train.csv,/mnt/extracted/data/lingualibre/lingua_libre_Q21-fra-French_train.csv,/mnt/extracted/data/cv-fr/clips/train.csv,/mnt/extracted/data/African_Accented_French/African_Accented_French/African_Accented_French_train.csv
++ sed -e 's/,$//g'
++ find /mnt/extracted/data/ -type f -name '*dev.csv' -printf %p,
+ all_dev_csv=/mnt/extracted/data/M-AILABS/fr_FR/fr_FR_dev.csv,/mnt/extracted/data/lingualibre/lingua_libre_Q21-fra-French_dev.csv,/mnt/extracted/data/cv-fr/clips/dev.csv,/mnt/extracted/data/African_Accented_French/African_Accented_French/African_Accented_French_dev.csv
++ sed -e 's/,$//g'
++ find /mnt/extracted/data/ -type f -name '*test.csv' -printf %p,
+ all_test_csv=/mnt/extracted/data/M-AILABS/fr_FR/fr_FR_test.csv,/mnt/extracted/data/lingualibre/lingua_libre_Q21-fra-French_test.csv,/mnt/extracted/data/cv-fr/clips/test.csv,/mnt/extracted/data/African_Accented_French/African_Accented_French/African_Accented_French_test.csv
+ mkdir -p /mnt/sources/feature_cache
+ '[' -f /transfer-checkpoint/checkpoint -a '!' -f /mnt/models/output_graph.pb ']'
+ '[' '!' -f /mnt/models/output_graph.pb ']'
+ EARLY_STOP_FLAG=--early_stop
+ '[' 1 = 0 ']'
+ python -u DeepSpeech.py --show_progressbar True --use_cudnn_rnn True --automatic_mixed_precision True --alphabet_config_path /mnt/models/alphabet.txt --lm_binary_path /mnt/lm/lm.binary --lm_trie_path /mnt/lm/trie --feature_cache /mnt/sources/feature_cache --train_files /mnt/extracted/data/M-AILABS/fr_FR/fr_FR_train.csv,/mnt/extracted/data/lingualibre/lingua_libre_Q21-fra-French_train.csv,/mnt/extracted/data/cv-fr/clips/train.csv,/mnt/extracted/data/African_Accented_French/African_Accented_French/African_Accented_French_train.csv --dev_files /mnt/extracted/data/M-AILABS/fr_FR/fr_FR_dev.csv,/mnt/extracted/data/lingualibre/lingua_libre_Q21-fra-French_dev.csv,/mnt/extracted/data/cv-fr/clips/dev.csv,/mnt/extracted/data/African_Accented_French/African_Accented_French/African_Accented_French_dev.csv --test_files /mnt/extracted/data/M-AILABS/fr_FR/fr_FR_test.csv,/mnt/extracted/data/lingualibre/lingua_libre_Q21-fra-French_test.csv,/mnt/extracted/data/cv-fr/clips/test.csv,/mnt/extracted/data/African_Accented_French/African_Accented_French/African_Accented_French_test.csv --train_batch_size 96 --dev_batch_size 96 --test_batch_size 96 --n_hidden 2048 --epochs 60 --learning_rate 0.0001 --dropout_rate 0.3 --lm_alpha 0.65 --lm_beta 1.45 --early_stop --checkpoint_dir /mnt/checkpoints/ --export_dir /mnt/models/ --export_language fra
WARNING:tensorflow:From /home/trainer/ds-train/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py:494: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.
    
W0116 12:57:23.120461 139891645953856 deprecation.py:323] From /home/trainer/ds-train/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py:494: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.

WARNING:tensorflow:From /home/trainer/ds-train/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:348: Iterator.output_types (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_types(iterator)`.
W0116 12:57:23.296478 139891645953856 deprecation.py:323] From /home/trainer/ds-train/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:348: Iterator.output_types (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_types(iterator)`.
WARNING:tensorflow:From /home/trainer/ds-train/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:349: Iterator.output_shapes (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_shapes(iterator)`.
W0116 12:57:23.296830 139891645953856 deprecation.py:323] From /home/trainer/ds-train/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:349: Iterator.output_shapes (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_shapes(iterator)`.
WARNING:tensorflow:From /home/trainer/ds-train/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:351: Iterator.output_classes (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_classes(iterator)`.
W0116 12:57:23.297110 139891645953856 deprecation.py:323] From /home/trainer/ds-train/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:351: Iterator.output_classes (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_classes(iterator)`.
I Enabling automatic mixed precision training.
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

W0116 12:57:34.538875 139891645953856 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /home/trainer/ds-train/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/python/layers/cudnn_rnn.py:342: calling GlorotUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0116 12:57:34.541965 139891645953856 deprecation.py:506] From /home/trainer/ds-train/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/python/layers/cudnn_rnn.py:342: calling GlorotUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From /home/trainer/ds-train/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0116 12:57:34.542365 139891645953856 deprecation.py:506] From /home/trainer/ds-train/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From /home/trainer/ds-train/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/python/layers/cudnn_rnn.py:345: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0116 12:57:34.542975 139891645953856 deprecation.py:506] From /home/trainer/ds-train/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/python/layers/cudnn_rnn.py:345: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:Entity <bound method _CudnnRNN.call of <tensorflow.contrib.cudnn_rnn.python.layers.cudnn_rnn.CudnnLSTM object at 0x7f3a13ba0710>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _CudnnRNN.call of <tensorflow.contrib.cudnn_rnn.python.layers.cudnn_rnn.CudnnLSTM object at 0x7f3a13ba0710>>: AttributeError: module 'gast' has no attribute 'Num'
W0116 12:57:34.636180 139891645953856 ag_logging.py:145] Entity <bound method _CudnnRNN.call of <tensorflow.contrib.cudnn_rnn.python.layers.cudnn_rnn.CudnnLSTM object at 0x7f3a13ba0710>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _CudnnRNN.call of <tensorflow.contrib.cudnn_rnn.python.layers.cudnn_rnn.CudnnLSTM object at 0x7f3a13ba0710>>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:From DeepSpeech.py:234: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0116 12:57:34.702176 139891645953856 deprecation.py:323] From DeepSpeech.py:234: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /home/trainer/ds-train/lib/python3.6/site-packages/tensorflow/python/training/slot_creator.py:193: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
W0116 12:57:35.542659 139891645953856 deprecation.py:323] From /home/trainer/ds-train/lib/python3.6/site-packages/tensorflow/python/training/slot_creator.py:193: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
WARNING:tensorflow:From /home/trainer/ds-train/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
W0116 12:57:35.898603 139891645953856 deprecation.py:323] From /home/trainer/ds-train/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from /mnt/checkpoints/train-17342
I0116 12:57:35.925405 139891645953856 saver.py:1280] Restoring parameters from /mnt/checkpoints/train-17342
I Restored variables from most recent checkpoint at /mnt/checkpoints/train-17342, step 17342
I STARTING Optimization
Epoch 0 |   Training | Elapsed Time: 0:14:51 | Steps: 1446 | Loss: 17.904373       
```

**Comment by lissyx** [comment] 2020-01-16 15:31
@GourmandGuedj Ok, `ds_ctcdecoder` is installed at build time, do you have those logs? We need to ensure the proper version was installed.

**Comment by GourmandGuedj** [comment] 2020-01-16 15:32
Oh now that you say it I might actually have change branch in the args of Docker build once, when I tried to use your DeepSpeech repo and branch validate_label_fr. 
Getting build logs in a minute

**Comment by GourmandGuedj** [comment] 2020-01-16 15:44
Is this it? 

```
Step 52/61 : RUN pip install `python util/taskcluster.py --decoder`
 ---> Running in 8ab06b176489
Collecting ds-ctcdecoder==0.6.0a15
  Downloading https://community-tc.services.mozilla.com/api/index/v1/task/project.deepspeech.deepspeech.native_client.v0.6.0-alpha.15.cpu-ctc/artifacts/public/ds_ctcdecoder-0.6.0a15-cp36-cp36m-manylinux1_x86_64.whl (5.6MB)
Requirement already satisfied: numpy>=1.7.0 in /home/trainer/ds-train/lib/python3.6/site-packages (from ds-ctcdecoder==0.6.0a15) (1.15.4)
Installing collected packages: ds-ctcdecoder
Successfully installed ds-ctcdecoder-0.6.0a15
Removing intermediate container 8ab06b176489
 ---> 7dd855f44321
```

**Comment by lissyx** [comment] 2020-01-16 15:45
> Is this it?
> 
> ```
> Step 52/61 : RUN pip install `python util/taskcluster.py --decoder`
>  ---> Running in 8ab06b176489
> Collecting ds-ctcdecoder==0.6.0a15
>   Downloading https://community-tc.services.mozilla.com/api/index/v1/task/project.deepspeech.deepspeech.native_client.v0.6.0-alpha.15.cpu-ctc/artifacts/public/ds_ctcdecoder-0.6.0a15-cp36-cp36m-manylinux1_x86_64.whl (5.6MB)
> Requirement already satisfied: numpy>=1.7.0 in /home/trainer/ds-train/lib/python3.6/site-packages (from ds-ctcdecoder==0.6.0a15) (1.15.4)
> Installing collected packages: ds-ctcdecoder
> Successfully installed ds-ctcdecoder-0.6.0a15
> Removing intermediate container 8ab06b176489
>  ---> 7dd855f44321
> ```

Yes. That seems to be the good version :/

**Comment by GourmandGuedj** [comment] 2020-01-16 15:47
Could that be because I started training the model on another branch with the wrong version, rebuild afterwards with the right one, and now it restores from checkpoints causing the error?

**Comment by lissyx** [comment] 2020-01-16 15:48
> Could that be because I started training the model on another branch with the wrong version, rebuild afterwards with the right one, and now it restores from checkpoints causing the error?

It's not unlikely :/

**Comment by GourmandGuedj** [comment] 2020-01-16 15:50
arf, i'll redo everything on the right branch then and let you know. Do you think I can at least skip the importing and just delete the checkpoints?

**Comment by lissyx** [comment] 2020-01-16 15:52
> arf, i'll redo everything on the right branch then and let you know. Do you think I can at least skip the importing and just delete the checkpoints?

Yes you can. Remove `lm/*` content as well, so it rebuilds the LM with proper version, delete `models/*` and it should be able to re-sue your checkpoints.

**Comment by GourmandGuedj** [comment] 2020-01-16 15:52
Ok will do. Thanks a lot, I'll let you know, probably tomorrow

**Comment by lissyx** [comment] 2020-01-16 15:55
@GourmandGuedj Check also the text files used to build the LM, it's possible there is still some code that does "> xx" to make them 0 byte, this is going to be an issue when you rebuild the LM. You may wanto remove those 0 byte files to properly rebuild the LM.

**Comment by GourmandGuedj** [comment] 2020-01-16 16:17
@lissyx ah just saw your comment, it is building now - are you talking about the sources_lm.txt files?

**Comment by lissyx** [comment] 2020-01-16 17:06
> @lissyx ah just saw your comment, it is building now - are you talking about the sources_lm.txt file?

Yep!

**Comment by lissyx** [comment] 2020-02-04 17:05
I think @GourmandGuedj told me it was fixed, and I could not reproduce the issue either. Closing.

**Closed by lissyx** 2020-02-04 17:05 UTC
