### ISSUE TITLE
Fail to run ./bin/run-tc-ldc93s1_new.sh 

### ISSUE THREAD

**Issue by GourmandGuedj** [Common-Voice/commonvoice-fr#84] opened 2020-01-13 14:01 UTC
Hello, 

I'm trying to build and run the Docker train image but it keeps failing at the last step of checks.sh:  
./bin/run-tc-ldc93s1_new.sh 2

I always get the following error: 

```
+ ./bin/run-tc-ldc93s1_new.sh 2
+ ldc93s1_dir=./data/ldc93s1-tc
+ ldc93s1_csv=./data/ldc93s1-tc/ldc93s1.csv
+ epoch_count=2
+ [ ! -f ./data/ldc93s1-tc/ldc93s1.csv ]
+ echo Downloading and preprocessing LDC93S1 example data, saving in ./data/ldc93s1-tc.
Downloading and preprocessing LDC93S1 example data, saving in ./data/ldc93s1-tc.
+ python -u bin/import_ldc93s1.py ./data/ldc93s1-tc
No path "./data/ldc93s1-tc" - creating ...
No archive "./data/ldc93s1-tc/LDC93S1.wav" - downloading...
Traceback (most recent call last):
  File "/home/trainer/ds-train/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/trainer/ds-train/lib/python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/home/trainer/ds-train/lib/python3.6/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/home/trainer/ds-train/lib/python3.6/site-packages/urllib3/connection.py", line 394, in connect
    ssl_context=context,
  File "/home/trainer/ds-train/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/trainer/ds-train/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/trainer/ds-train/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/trainer/ds-train/lib/python3.6/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='catalog.ldc.upenn.edu', port=443): Max retries exceeded with url: /desc/addend
a/LDC93S1.wav (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "bin/import_ldc93s1.py", line 28, in <module>
    _download_and_preprocess_data(sys.argv[1])
  File "bin/import_ldc93s1.py", line 18, in _download_and_preprocess_data
    local_file = maybe_download(LDC93S1_BASE + ".wav", data_dir, LDC93S1_BASE_URL + LDC93S1_BASE + ".wav")
  File "/home/trainer/ds/bin/../util/downloader.py", line 18, in maybe_download
    req = requests.get(archive_url, stream=True)
  File "/home/trainer/ds-train/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/trainer/ds-train/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/trainer/ds-train/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/trainer/ds-train/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/trainer/ds-train/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='catalog.ldc.upenn.edu', port=443): Max retries exceeded with url: /desc/addenda/LD
C93S1.wav (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
```

Do you know what may cause this and how to resolve? 
Thanks!

**Comment by lissyx** [comment] 2020-01-13 15:23
> Do you know what may cause this and how to resolve?

That seems to be an issue on your side:
```
 python bin/import_ldc93s1.py data/ldc93s1-tc/
No path "data/ldc93s1-tc/" - creating ...
No archive "data/ldc93s1-tc/LDC93S1.wav" - downloading...
Progress |                                                                                                                                                                                                                                                                                                                                                                                           | N/A% completedNo archive "data/ldc93s1-tc/LDC93S1.txt" - downloading...
Progress |###########################################################################################################################################################################################################################################################################################################################################################################################| 100% completed
Progress |###########################################################################################################################################################################################################################################################################################################################################################################################| 100% completed
```

**Comment by lissyx** [comment] 2020-01-13 15:28
> I'm trying to build and run the Docker train image

Can you share your commands ? It looks like the server's certificate was updated and is not valid before 10/01/2020, can you ensure your system clock is not wrong as well ?

**Comment by GourmandGuedj** [comment] 2020-01-13 15:38
Sure i'm just running 

`docker run --tty --runtime=nvidia --mount type=bind,src=/home/gabrielcloud75/hostdir,dst=/mnt 6863d19245f2` on my VM. 

Just checked my system clock which seems to be fine : 

`$ date
Mon Jan 13 15:34:56 UTC 2020`

My setup is a GCP VM with Debian 9 with a NVIDIA V100 GPU

**Comment by lissyx** [comment] 2020-01-13 15:47
> Sure i'm just running
> 
> `docker run --tty --runtime=nvidia --mount type=bind,src=/home/gabrielcloud75/hostdir,dst=/mnt 6863d19245f2` on my VM.

And how do you build ?

> 
> Just checked my system clock which seems to be fine :
> 
> `$ date Mon Jan 13 15:34:56 UTC 2020`
> 
> My setup is a GCP VM with Debian 9 with a NVIDIA V100 GPU

I just rebuilt the Docker image to make sure, and it's working well here. The error is system/network related, not much I can do there.

**Comment by lissyx** [comment] 2020-01-13 15:48
@GourmandGuedj Try and remove the call to `./bin/run-tc-ldc93s1_new.sh` in `checks.sh`, it won't verify that your CUDA setup is okay, but if it's a network/system issue related to GCP it should unblock.

**Comment by GourmandGuedj** [comment] 2020-01-13 15:55
Yup that's what I did, i'm currently at the import of common voice fr data step, i'll let you know if I encounter any issues but should be good. Thanks a lot for your help @lissyx

**Comment by GourmandGuedj** [comment] 2020-01-13 15:56
> > Sure i'm just running
> > `docker run --tty --runtime=nvidia --mount type=bind,src=/home/gabrielcloud75/hostdir,dst=/mnt 6863d19245f2` on my VM.
> 
> And how do you build ?
> 
> > Just checked my system clock which seems to be fine :
> > `$ date Mon Jan 13 15:34:56 UTC 2020`
> > My setup is a GCP VM with Debian 9 with a NVIDIA V100 GPU
> 
> I just rebuilt the Docker image to make sure, and it's working well here. The error is system/network related, not much I can do there.

I build just as documented `docker build -f Dockerfile.train .`

**Comment by lissyx** [comment] 2020-01-13 16:04
> > > Sure i'm just running
> > > `docker run --tty --runtime=nvidia --mount type=bind,src=/home/gabrielcloud75/hostdir,dst=/mnt 6863d19245f2` on my VM.
> > 
> > 
> > And how do you build ?
> > > Just checked my system clock which seems to be fine :
> > > `$ date Mon Jan 13 15:34:56 UTC 2020`
> > > My setup is a GCP VM with Debian 9 with a NVIDIA V100 GPU
> > 
> > 
> > I just rebuilt the Docker image to make sure, and it's working well here. The error is system/network related, not much I can do there.
> 
> I build just as documented `docker build -f Dockerfile.train .`

Right. Depending on how you progress and if you want to reproduce exactly my model, you may want to add: `--build-arg ds_repo=lissyx/DeepSpeech --build-arg ds_branch=validate_label_fr`, it's local changes to cleanup a bit of Common Voice and other dataset.

We don't yet have a proper story to deal with that at DeepSpeech level, so for now it's still in a fork.

**Comment by GourmandGuedj** [comment] 2020-01-13 16:08
Ok duely noted, I'll try with these. 

Also I just made a PR to correct the build command in the contributing.md page which still have the old Dockerfile.train.fr

Thanks again for the quick help here

**Comment by lissyx** [comment] 2020-01-24 11:40
I think you told me this was fixed. Closing.

**Closed by lissyx** 2020-01-24 11:40 UTC
